# Generated by Django 4.2.11 on 2024-03-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_images_instagram_about_image_1_about_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='track_background',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='images',
            name='track_result_background',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
