# Generated by Django 4.2.11 on 2024-03-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_footer_industryserved_about_annually_tons_of_cargo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='industryServed',
            new_name='Industry',
        ),
    ]
