# Generated by Django 4.2.11 on 2024-04-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
