# Generated by Django 4.2.11 on 2024-03-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='release_status',
            new_name='steam_release_status',
        ),
        migrations.AddField(
            model_name='track',
            name='customs_release_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
