# Generated by Django 4.2.11 on 2024-04-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_rename_release_status_track_steam_release_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='arrival_date_to_transit_port',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='arrival_to_final_destination',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='consignee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='container_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='date_of_arriving_to_warehouse',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='dispatch_date_to_final_port',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='dispatched_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='hbl_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='load_on_rail',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='mbl_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='pick_up_date_of_warehouse',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='port_of_discharge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='port_of_loading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='shipper',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='steam_release_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='transit_port',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='voyage_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
